apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: novasec-enforce-network-boundaries
  annotations:
    policies.kyverno.io/title: Enforce Network Boundaries
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Namespace
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Validates that non-system namespaces declare a default-deny
      NetworkPolicy annotation and carry a tenant isolation label.
      NIST 800-53: SC-7 (Boundary Protection)
      FedRAMP Moderate Baseline
    novasec.cloud/control: SC-7
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-network-policy-annotation
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              names:
                - kube-system
                - kube-public
                - kube-node-lease
                - gatekeeper-system
                - falco
                - monitoring
                - istio-system
      validate:
        message: >-
          SC-7: Namespace must have annotation
          'novasec.cloud/network-policy: default-deny' confirming
          a default-deny NetworkPolicy is applied.
        pattern:
          metadata:
            annotations:
              novasec.cloud/network-policy: default-deny
    - name: require-tenant-label-on-namespace
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              names:
                - kube-system
                - kube-public
                - kube-node-lease
                - gatekeeper-system
                - falco
                - monitoring
                - istio-system
      validate:
        message: >-
          SC-7: Namespace must have label 'novasec.cloud/tenant' for
          NetworkPolicy-based tenant isolation.
        pattern:
          metadata:
            labels:
              novasec.cloud/tenant: "?*"
    - name: block-nodeport-services
      match:
        any:
          - resources:
              kinds:
                - Service
      validate:
        message: >-
          SC-7: NodePort services are not allowed. Use ClusterIP with
          Ingress for controlled boundary access.
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.type }}"
                operator: Equals
                value: NodePort
